# -*- coding: utf-8 -*-
"""Batch 3 — mineral & energy drinks + the kvass ferment.
Key verdicts carried from TAXONOMY-SYNERGY.md:
- A.1 #5: 'Adrenal Cocktail' retitled Mineral Refresher (file name unchanged);
  'adrenal fatigue' framing replaced with plain electrolytes + vitamin C, and the
  rename explained honestly on the card (research-backed chip with the debunk sources).
- A.2: broth reframed as collagen/glycine + comfort (NOT an iron/mineral rebuilder);
  plant omega-3 written as ALA; morning-waters 'hair' claim dropped; kvass leads
  with folate, non-iodised salt + submerged beets carried as safety.
"""

from data_teas import USDA, ODS_IRON, CAMBRIDGE_VITC, ODS_MAG, BANYAN

ODS_VITC = '<a href="https://ods.od.nih.gov/factsheets/VitaminC-HealthProfessional/" target="_blank" rel="noopener">NIH — Vitamin C fact sheet (2021)</a>'
ODS_POTASSIUM = '<a href="https://ods.od.nih.gov/factsheets/Potassium-HealthProfessional/" target="_blank" rel="noopener">NIH — Potassium fact sheet</a>'
ODS_ZINC = '<a href="https://ods.od.nih.gov/factsheets/Zinc-HealthProfessional/" target="_blank" rel="noopener">NIH — Zinc fact sheet (2022)</a>'
ODS_CHOLINE = '<a href="https://ods.od.nih.gov/factsheets/Choline-HealthProfessional/" target="_blank" rel="noopener">NIH — Choline fact sheet (lactation needs are the highest of any life stage)</a>'
INFANTRISK_CHOLINE = '<a href="https://infantrisk.com/content/choline-during-pregnancy-lactation" target="_blank" rel="noopener">InfantRisk — choline during pregnancy &amp; lactation</a>'
HARVARD_FLAX = '<a href="https://www.health.harvard.edu/heart-health/why-not-flaxseed-oil" target="_blank" rel="noopener">Harvard Health — plant ALA converts poorly to DHA</a>'
ADRENAL_REVIEW = '<a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC4997656/" target="_blank" rel="noopener">PMC4997656 — systematic review: "adrenal fatigue" does not exist as a diagnosis</a>'
ENDOCRINE = '<a href="https://www.endocrine.org/patient-engagement/endocrine-library/adrenal-fatigue" target="_blank" rel="noopener">Endocrine Society — adrenal fatigue is not a recognised condition</a>'
BROTH_SPRINGER = '<a href="https://link.springer.com/article/10.1007/s00217-024-04556-2" target="_blank" rel="noopener">European Food Research &amp; Technology (2024) — bone-broth composition analysis</a>'
BROTH_PMC = '<a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC5533136/" target="_blank" rel="noopener">PMC5533136 — minerals in bone broth are modest &amp; variable</a>'
BCCDC = '<a href="https://www.bccdc.ca/resource-gallery/Documents/Educational%20Materials/EH/FPS/Food/Fermented/Fermented_Foods_Guidance-3.1_Fermented_Vegetables.pdf" target="_blank" rel="noopener">BCCDC — fermented vegetables: safe home-fermentation guidance (PDF)</a>'

DRINKS = [

# ---------------------------------------------------------------- morning waters
{
 "slug": "morning-waters",
 "name": "Morning Waters",
 "eyebrow": "Morning tonic <span class='dot'>·</span> Keep your milk flowing <span class='dot'>·</span> On waking",
 "sub": "Three simple warm-water sips to open the day — Mum picks her water by how she feels.",
 "hero_alt": "Three glasses of warm morning waters with amla, ajwain and lemon",
 "time": "about 5 min",
 "makes": "1 cup",
 "keep": "make it fresh on waking",
 "when": "On waking, on an empty stomach — 20–30 min before food. Warm, never iced.",
 "why": [
  {"text": "Amla — Ayurveda's sour vitamin-C berry, stirred into the first water of the day", "chip": "t", "ev": "amla"},
  {"text": "Vitamin C taken with an iron meal lifts how much iron you absorb — 2–3&times;", "chip": "rb", "ev": "vitc"},
  {"text": "Ajwain — the traditional after-birth digestive seed, steeped warm", "chip": "t", "ev": "ajwain"},
  {"text": "Warm water on an empty stomach — gentle on a healing gut"},
 ],
 "bfnote": None,
 "ev": {
  "amla": {"cls": "t", "chip": "tradition", "title": "Amla — the sour morning berry",
   "meaning": "Tradition, honestly labelled. Amla (Indian gooseberry) is one of Ayurveda's most-used fruits, famously rich in vitamin C and taken as a sour morning water. The tradition is real and the berry genuinely carries vitamin C — the ritual framing is tradition, and we keep it that way.",
   "src": [BANYAN, "Classical Ayurvedic practice — amla as a daily rasayana"]},
  "vitc": {"cls": "rb", "chip": "research-backed", "title": "Vitamin C unlocks the iron in your meals",
   "meaning": "Research-backed. Vitamin C taken alongside plant (non-heme) iron reliably raises how much of it your body absorbs — meta-analysis puts it around two to three times more from that meal. That's why the amla or lemon water sits next to breakfast, not instead of it.",
   "src": [CAMBRIDGE_VITC, ODS_IRON]},
  "ajwain": {"cls": "t", "chip": "tradition", "title": "Ajwain — the postpartum seed water",
   "meaning": "Tradition, honestly labelled. Ajwain (carom seed) water is the standard South-Asian postpartum morning sip for bloating and sluggish digestion — a kitchen-spice dose, steeped and strained. Centuries of confinement-kitchen use; not measured in trials.",
   "src": ["Traditional South-Asian postpartum practice — ajwain water in the confinement weeks", BANYAN]},
 },
 "serve": {"label": "Which water today", "items": [
   {"k": "amla", "label": "amla — the vitamin-C one", "on": True},
   {"k": "ajwain", "label": "ajwain — the de-bloating one", "on": False},
   {"k": "lemon", "label": "lemon — the simple one", "on": False},
  ]},
 "boost": {"label": "Make it PP Gold (for yourself)", "items": [
   {"k": "honey", "label": "a little honey", "small": "if amla is too sour straight", "on": False},
   {"k": "iron", "label": "pair it with an iron breakfast", "small": "that's when the vitamin C works", "on": True},
  ], "note": "One cup, one water — rotate by how the morning feels."},
 "when_opts": {"label": "For", "opts": ["On waking"], "sel": "On waking"},
 "ings": [
  {"k": "water", "n": "Warm filtered water", "q": "1 cup", "img": "img/morning-waters/ing-04-warm-filtered-water.jpg", "prep": "warm, not hot"},
  {"k": "amla", "n": "Amla powder", "q": "½ tsp", "img": "img/morning-waters/ing-01-amla-powder.jpg", "opt": True},
  {"k": "ajwain", "n": "Ajwain seeds", "q": "½ tsp", "img": "img/morning-waters/ing-02-ajwain-seeds.jpg", "opt": True},
  {"k": "lemon", "n": "Lemon", "q": "½", "img": "img/morning-waters/ing-03-lemon.jpg", "opt": True},
  {"k": "honey", "n": "Honey", "q": "a little", "img": "img/morning-waters/ing-05-honey.jpg", "opt": True},
 ],
 "method": [
  {"ic": "Check Mum's pick", "verb": "Which water did Mum ask for?",
   "detail": "Mum picks <b>one</b> each morning: <b>amla</b> (vitamin C), <b>ajwain</b> (bloating), or <b>lemon</b> (simple). Warm a cup of water — warm, <b>not hot</b>.",
   "done": "one warm cup, one chosen water.",
   "say": "Check which water Mum asked for this morning, and warm a cup of water. Warm, not hot."},
  {"ic": "Make her water", "verb": "Stir, steep or squeeze",
   "detail": "<b>Amla:</b> stir in ½ tsp until it disappears. <b>Ajwain:</b> steep ½ tsp seeds 5 min, then strain. <b>Lemon:</b> squeeze half a lemon in.",
   "timer": [{"label": "Ajwain steep", "min": 5}],
   "done": "cloudy-sour (amla), golden (ajwain), or bright (lemon).",
   "say": "For amla, stir the powder in. For ajwain, steep the seeds five minutes and strain. For lemon, squeeze half a lemon in."},
  {"ic": "Before breakfast", "verb": "To Mum — before food",
   "detail": "Take it to Mum <b>20–30 min before breakfast</b>. A little <b>honey</b> only if she asked.",
   "done": "sipped warm, breakfast still to come.",
   "say": "Take it to Mum twenty to thirty minutes before breakfast."},
 ],
 "overview_method": [
  "Warm a cup of water — not hot.",
  "Mum's pick: amla stirred / ajwain steeped / lemon squeezed.",
  "To her 20–30 min before breakfast.",
 ],
 "nutri": [
  {"v": "Vitamin C", "k": "amla &amp; lemon days"},
  {"v": "Caffeine", "k": "none"},
  {"v": "Warm", "k": "never iced"},
 ],
},

# ---------------------------------------------------------------- mineral refresher (file: adrenal-cocktail.html)
{
 "slug": "adrenal-cocktail",
 "name": "Mineral Refresher",
 "eyebrow": "Mineral tonic <span class='dot'>·</span> Keep your milk flowing <span class='dot'>·</span> The 3pm glass",
 "sub": "Orange juice, coconut water, cream of tartar &amp; sea salt — the electrolytes night feeds drink down. (You may know it as the &lsquo;adrenal cocktail&rsquo;.)",
 "hero_alt": "A bright glass of orange mineral refresher",
 "time": "about 2 min",
 "makes": "1 glass",
 "keep": "drink it fresh",
 "when": "Mid-morning or the afternoon dip, between meals — not a bedtime drink.",
 "why": [
  {"text": "Orange juice — vitamin C &amp; potassium", "chip": "rb", "ev": "oj"},
  {"text": "Coconut water + cream of tartar — a genuinely potassium-rich pair", "chip": "rb", "ev": "potassium"},
  {"text": "A pinch of sea salt — sodium, the other half of fluid balance"},
  {"text": "Why not &lsquo;adrenal&rsquo;? Because &lsquo;adrenal fatigue&rsquo; isn&rsquo;t a recognised condition — the drink doesn&rsquo;t need the myth", "chip": "rb", "ev": "honest"},
 ],
 "bfnote": {"text": "Breastfeeding is thirsty work — fluids and minerals genuinely matter to how you feel. This glass is hydration that tastes like looking after yourself; reach for it instead of a second coffee.", "ev": "bf"},
 "ev": {
  "oj": {"cls": "rb", "chip": "research-backed", "title": "Orange juice — vitamin C &amp; potassium",
   "meaning": "Research-backed on composition. Half a cup of orange juice carries measurable vitamin C and potassium — real nutrients, no mystique needed.",
   "src": [USDA("orange juice, fresh (nutrient data)"), ODS_VITC]},
  "potassium": {"cls": "rb", "chip": "research-backed", "title": "The potassium pair",
   "meaning": "Research-backed on composition. Coconut water is a naturally potassium-rich drink, and cream of tartar (potassium bitartrate) is one of the most concentrated food sources of potassium there is. Together with the salt pinch, this is a simple, real electrolyte glass.",
   "src": [USDA("coconut water &amp; cream of tartar (nutrient data)"), ODS_POTASSIUM]},
  "honest": {"cls": "rb", "chip": "research-backed", "title": "Why we renamed this drink",
   "meaning": "Research-backed — in the other direction. 'Adrenal fatigue' is not a recognised medical condition: a systematic review found no evidence it exists, and endocrinologists say the same. The drink never needed the story — it's a good electrolyte + vitamin C glass for a depleted, thirsty season. So we kept the recipe and retired the name.",
   "src": [ADRENAL_REVIEW, ENDOCRINE]},
  "bf": {"cls": "b", "chip": "breastfeeding note", "title": "Fluids while breastfeeding",
   "meaning": "Breastfeeding note — a care flag, not a grade. Milk-making raises your fluid needs, and thirst can hide behind tiredness in week one. A mineral glass mid-afternoon is a kind habit — alongside water, not instead of it. (Vitamin C is mildly energising, so keep it out of the bedtime hour.)",
   "src": [ODS_VITC]},
 },
 "boost": {"label": "Make it PP Gold (for yourself)", "items": [
   {"k": "fresh", "label": "squeeze the orange fresh", "small": "brighter, more vitamin C", "on": True},
   {"k": "ice", "label": "cool, not iced", "small": "gentler on a healing gut", "on": True},
  ], "note": "Between feeds is its moment — the glass you drink sitting down."},
 "when_opts": {"label": "For", "opts": ["Mid-morning", "Mid-afternoon"], "sel": "Mid-afternoon"},
 "ings": [
  {"k": "oj", "n": "Orange juice", "q": "½ cup", "img": "img/adrenal-cocktail/ing-01-orange-juice.jpg", "prep": "fresh is best"},
  {"k": "coconut", "n": "Coconut water", "q": "½ cup", "img": "img/adrenal-cocktail/ing-02-coconut-water.jpg"},
  {"k": "tartar", "n": "Cream of tartar", "q": "⅛ tsp", "img": "img/adrenal-cocktail/ing-03-cream-of-tartar.jpg"},
  {"k": "salt", "n": "Sea salt", "q": "a pinch", "img": "img/adrenal-cocktail/ing-04-sea-salt.jpg"},
 ],
 "method": [
  {"ic": "Pour", "verb": "Pour the two juices",
   "detail": "<b>½ cup orange juice</b> and <b>½ cup coconut water</b> into a glass.",
   "done": "a bright, sunny glass.",
   "say": "Pour the orange juice and the coconut water into a glass."},
  {"ic": "Minerals in", "verb": "Stir the minerals in",
   "detail": "Add <b>⅛ tsp cream of tartar</b> and <b>a pinch of sea salt</b>. Stir until nothing sits on the bottom.",
   "done": "fully dissolved — no grit at the bottom.",
   "say": "Add the cream of tartar and a pinch of sea salt, and stir until it all disappears."},
  {"ic": "Take it to Mum", "verb": "To Mum, between feeds",
   "detail": "Take it to her cool (not iced), <b>between meals</b> — the mid-afternoon dip is its moment.",
   "done": "Mum sitting down with a full glass.",
   "say": "Take it to Mum cool, between meals. The mid-afternoon dip is its moment."},
 ],
 "overview_method": [
  "Pour the orange juice + coconut water.",
  "Stir in cream of tartar + a pinch of salt.",
  "To Mum, between feeds — not bedtime.",
 ],
 "nutri": [
  {"v": "Potassium", "k": "the point of it"},
  {"v": "Vitamin C", "k": "from the orange"},
  {"v": "Caffeine", "k": "none"},
 ],
 "nutri_label": "In this glass",
},

# ---------------------------------------------------------------- power smoothie
{
 "slug": "power-smoothie",
 "name": "Power Smoothie",
 "eyebrow": "Smoothie <span class='dot'>·</span> Steady energy <span class='dot'>·</span> Max-boost",
 "sub": "A maxed-out blend — protein, seeds &amp; fruit in one glass, built for the afternoon dip.",
 "hero_alt": "A tall glass of berry power smoothie",
 "time": "about 3 min",
 "makes": "1 large glass",
 "keep": "drink it fresh",
 "when": "Mid-morning or the afternoon dip — when energy flags and lunch feels far away.",
 "why": [
  {"text": "Collagen or whey — a real scoop of protein, the building blocks for repair", "chip": "rb", "ev": "protein"},
  {"text": "Chia, hemp, pumpkin &amp; flax — plant omega-3 (ALA), magnesium &amp; zinc", "chip": "rb", "ev": "seeds"},
  {"text": "Berries — vitamin C &amp; colour", "chip": "rb", "ev": "berries"},
  {"text": "Banana &amp; dates — the sweetness and the staying power"},
 ],
 "bfnote": None,
 "ev": {
  "protein": {"cls": "rb", "chip": "research-backed", "title": "The protein scoop",
   "meaning": "Research-backed on composition. A scoop of collagen or whey is measurable protein — the building blocks your body uses for repair and milk-making. We claim the blocks, not miracle outcomes.",
   "src": [USDA("whey &amp; collagen protein (nutrient data)")]},
  "seeds": {"cls": "rb", "chip": "research-backed", "title": "The seed mix — ALA, magnesium &amp; zinc",
   "meaning": "Research-backed on composition — with one honest asterisk. The seeds measurably carry magnesium, zinc and plant omega-3 (ALA). ALA converts poorly to the DHA that builds baby brains, so for the brain story eat the sardine and salmon cards; these seeds earn their place on minerals.",
   "src": [ODS_ZINC, ODS_MAG, HARVARD_FLAX]},
  "berries": {"cls": "rb", "chip": "research-backed", "title": "Berries — vitamin C",
   "meaning": "Research-backed on composition. Half a cup of blueberries brings vitamin C and polyphenols — and makes the whole glass taste like a treat instead of a chore.",
   "src": [USDA("blueberries (nutrient data)"), ODS_VITC]},
 },
 "boost": {"label": "Make it PP Gold (for yourself)", "items": [
   {"k": "spinach", "label": "a handful of spinach", "small": "folate — you won't taste it", "on": True},
   {"k": "nutbutter", "label": "a spoon of nut butter", "small": "keeps you full longer", "on": False},
   {"k": "mct", "label": "a little MCT oil", "small": "steady fuel", "on": False},
  ], "note": "Take out anything you don't fancy — the glass survives every edit."},
 "when_opts": {"label": "For", "opts": ["Mid-morning", "Afternoon"], "sel": "Afternoon"},
 "ings": [
  {"k": "banana", "n": "Banana", "q": "1", "img": "img/power-smoothie/ing-01-banana.jpg"},
  {"k": "berries", "n": "Blueberries", "q": "½ cup", "img": "img/power-smoothie/ing-02-blueberries.jpg"},
  {"k": "milk", "n": "Milk / coconut milk", "q": "1 cup", "img": "img/power-smoothie/ing-03-milk-coconut-milk.jpg"},
  {"k": "protein", "n": "Collagen / whey", "q": "1 scoop", "img": "img/power-smoothie/ing-04-collagen-whey.jpg"},
  {"k": "seeds", "n": "Chia, hemp + pumpkin seeds", "q": "2 tbsp", "img": "img/power-smoothie/ing-05-chia-hemp-pumpkin-seeds.jpg"},
  {"k": "flax", "n": "Ground flax", "q": "1 tbsp", "img": "img/power-smoothie/ing-06-ground-flax.jpg"},
  {"k": "dates", "n": "Dates", "q": "2, pitted", "img": "img/power-smoothie/ing-07-dates.jpg"},
 ],
 "method": [
  {"ic": "Load the blender", "verb": "Fruit &amp; milk in",
   "detail": "<b>Banana, blueberries, dates</b> and <b>1 cup milk</b> into the blender.",
   "done": "blender loaded, lid found.",
   "say": "Put the banana, blueberries, dates and the milk into the blender."},
  {"ic": "Add the boosters", "verb": "The scoop &amp; the seeds",
   "detail": "Add the <b>protein scoop</b>, <b>2 tbsp seed mix</b> and <b>1 tbsp ground flax</b> — plus <b>a handful of spinach</b> if Mum asked (she won't taste it).",
   "done": "everything in, seeds on top.",
   "say": "Add the protein scoop, the seed mix and the ground flax. A handful of spinach too if Mum asked."},
  {"ic": "Blend & pour", "verb": "Blend it smooth — 1 min",
   "detail": "Blend until completely smooth; thin with a splash of milk or water if it's too thick to sip.",
   "timer": [{"label": "Blend", "min": 1}],
   "done": "pourable, no seed grit.",
   "say": "Blend until completely smooth, and thin it with a splash of milk if it's too thick."},
 ],
 "overview_method": [
  "Fruit, dates &amp; milk into the blender.",
  "Add protein scoop, seeds, flax.",
  "Blend smooth; thin to taste.",
 ],
 "nutri": [
  {"v": "Protein", "k": "a full scoop"},
  {"v": "Mg + Zn", "k": "from the seeds"},
  {"v": "Omega-3", "k": "plant ALA — named honestly"},
 ],
 "nutri_label": "In this glass",
},

# ---------------------------------------------------------------- meat stock latte
{
 "slug": "meat-stock-latte",
 "name": "Meat Stock Latte",
 "eyebrow": "Savoury tonic <span class='dot'>·</span> Heal your gut <span class='dot'>·</span> Run-down days",
 "sub": "A warm, frothy, egg-enriched cup of stock — the savoury pick-me-up for days you can't face food.",
 "hero_alt": "A frothy mug of golden meat stock latte",
 "time": "about 5 min",
 "makes": "1 mug",
 "keep": "drink it fresh &amp; warm",
 "when": "Run-down days, or a cold coming on — warm, savoury, gentle when eating feels like work.",
 "why": [
  {"text": "Well-gelled stock — collagen &amp; glycine, warm comfort that counts as fluids", "chip": "rb", "ev": "stock"},
  {"text": "Egg yolks — protein &amp; choline, the quiet star of the cup", "chip": "rb", "ev": "yolks"},
  {"text": "Ghee — the silky carrier fat", "chip": "t", "ev": "ghee"},
  {"text": "Savoury &amp; warm — for the days sweet is unthinkable"},
 ],
 "bfnote": {"text": "Choline needs are at their life-long highest while breastfeeding, and egg yolks are one of the best food sources there is — this odd little latte genuinely earns its keep.", "ev": "bf"},
 "ev": {
  "stock": {"cls": "rb", "chip": "research-backed", "title": "Stock — collagen &amp; glycine, honestly framed",
   "meaning": "Research-backed on composition — and honestly bounded. A well-gelled stock measurably carries collagen-derived protein (gelatin) and glycine. What it does NOT carry much of is minerals or iron — analyses show those are modest and variable, so we frame this cup as repair building-blocks, warmth and fluids, and leave the iron story to the meat and liver cards.",
   "src": [BROTH_SPRINGER, BROTH_PMC]},
  "yolks": {"cls": "rb", "chip": "research-backed", "title": "Egg yolks — protein &amp; choline",
   "meaning": "Research-backed. Egg yolks are among the richest food sources of choline — a nutrient breastfeeding draws on heavily (lactation needs are the highest of any life stage). Two yolks make this a real pick-me-up, not just warm broth.",
   "src": [ODS_CHOLINE, INFANTRISK_CHOLINE]},
  "ghee": {"cls": "t", "chip": "tradition", "title": "Ghee — the carrier",
   "meaning": "Tradition, honestly labelled. Ghee makes the cup silky and carries the fat-soluble vitamins that ride with fat. The froth is the point — it drinks like a latte, not a soup.",
   "src": ["Traditional use of ghee as the postpartum kitchen fat", BANYAN]},
  "bf": {"cls": "b", "chip": "breastfeeding note", "title": "Choline while breastfeeding",
   "meaning": "Breastfeeding note — a care flag in your favour. Choline requirements are higher during lactation than at any other time of life (550 mg/day), and most mothers fall short. Egg yolks are one of the best sources — a two-yolk cup is a meaningful contribution, not a garnish.",
   "src": [ODS_CHOLINE, INFANTRISK_CHOLINE]},
 },
 "boost": {"label": "Make it PP Gold (for yourself)", "items": [
   {"k": "gelatin", "label": "a scoop of beef gelatin", "small": "extra collagen blocks", "on": True},
   {"k": "turmeric", "label": "a pinch of turmeric + pepper", "small": "the golden version", "on": False},
  ], "note": "This is your cup — the family gets dinner, you get the latte."},
 "when_opts": {"label": "For", "opts": ["Mid-morning", "Afternoon", "A run-down moment"], "sel": "A run-down moment"},
 "ings": [
  {"k": "stock", "n": "Meat stock", "q": "2 cups", "img": "img/meat-stock-latte/ing-01-meat-stock.jpg", "prep": "warm, well-gelled"},
  {"k": "yolks", "n": "Egg yolks", "q": "2", "img": "img/meat-stock-latte/ing-02-egg-yolks.jpg", "prep": "the freshest eggs"},
  {"k": "ghee", "n": "Ghee", "q": "1 spoon", "img": "img/meat-stock-latte/ing-03-ghee.jpg"},
  {"k": "salt", "n": "Sea salt", "q": "a pinch", "img": "img/meat-stock-latte/ing-04-sea-salt.jpg"},
 ],
 "method": [
  {"ic": "Warm the stock", "verb": "Warm the stock — not boiling",
   "detail": "Gently warm <b>2 cups meat stock</b> — warm enough to steam, <b>never boiling</b> (boiling scrambles the yolks in the next step).",
   "done": "steaming, no bubbles.",
   "say": "Gently warm the meat stock. Warm enough to steam, never boiling."},
  {"ic": "Blend", "verb": "Blend — yolks, ghee, salt",
   "detail": "Into a blender (or a jar for the stick blender): the warm stock, <b>2 egg yolks</b>, <b>a spoon of ghee</b> and <b>a pinch of salt</b>.",
   "warn": {"b": "The yolks stay barely cooked.", "text": "Use the freshest eggs you have (or pasteurised) — and wash hands after separating them."},
   "done": "everything in the jug, yolks whole.",
   "say": "Put the warm stock, the egg yolks, the ghee and a pinch of salt into the blender."},
  {"ic": "Froth & take it up", "verb": "Whizz 30 sec — pour it frothy",
   "detail": "Blend about <b>30 seconds</b>, until smooth with a real froth on top. Pour into a mug and take it to Mum warm.",
   "timer": [{"label": "Blend", "min": 1}],
   "done": "golden, frothy, latte-looking.",
   "say": "Blend for about thirty seconds until frothy, pour into a mug, and take it to Mum warm."},
 ],
 "overview_method": [
  "Warm the stock — never boiling.",
  "Blend with yolks, ghee, salt.",
  "30 sec froth; pour; take it up.",
 ],
 "nutri": [
  {"v": "Choline", "k": "2 yolks · the star"},
  {"v": "Collagen", "k": "gelled stock"},
  {"v": "Caffeine", "k": "none"},
 ],
},

# ---------------------------------------------------------------- beet kvass (ferment)
{
 "slug": "beet-kvass-card",
 "name": "Beet Kvass",
 "eyebrow": "Ferment <span class='dot'>·</span> Rebuild your blood <span class='dot'>·</span> A small glass a day",
 "sub": "A ruby, salty-tangy brine tonic — folate from the beets, live cultures from the ferment.",
 "hero_alt": "A Kilner jar of ruby beet kvass",
 "time": "hands-on 10 min",
 "makes": "~1 L",
 "keep": "weeks in the fridge — cold slows the ferment right down",
 "when": "A small glass on waking, or before a meal — daily once the jar is ready.",
 "meta_line": "Hands-on 10 min &middot; ready in <b>3–5 days</b> &middot; makes ~<b>1 L</b>",
 "finish_head": "Jar started?",
 "finish_btn": "Jar started &mdash; tell Mum",
 "finish_cap": "Mum gets a note that the jar clock is running.",
 "after_line": "Sent to Mum &mdash; day one starts now.",
 "last_next": "Done &mdash; jar away",
 "why": [
  {"text": "Beetroot — folate to help rebuild blood, with a gentle share of iron", "chip": "rb", "ev": "beets"},
  {"text": "A living lacto-ferment — the salt brine grows the same cultures as sauerkraut", "chip": "rb", "ev": "ferment"},
  {"text": "The traditional first-40-days tonic of Eastern-European kitchens", "chip": "t", "ev": "trad"},
  {"text": "Salty-tangy, essentially alcohol-free — a brine ferment, not a sugary kvass"},
 ],
 "bfnote": {"text": "A small glass a day is the tradition — it's salty, so it counts as your savoury sip, not your water. Start with half a glass and see how you both feel.", "ev": "bf"},
 "ev": {
  "beets": {"cls": "rb", "chip": "research-backed", "title": "Beetroot — folate first",
   "meaning": "Research-backed on composition — framed honestly. Beetroot is genuinely rich in folate, a blood-building B-vitamin; its iron is real but modest. We lead with the folate and let the liver and meat cards carry the iron story.",
   "src": [USDA("beets, raw (folate &amp; iron data)")]},
  "ferment": {"cls": "rb", "chip": "research-backed", "title": "A living lacto-ferment",
   "meaning": "Research-backed on the method. A salt brine over vegetables reliably grows lactic-acid cultures — the same safe, ancient process as sauerkraut, and public-health guidance describes exactly how to do it safely at home. Whether daily ferments improve a given gut is individual — we claim the living cultures, not a cure.",
   "src": [BCCDC]},
  "trad": {"cls": "t", "chip": "tradition", "title": "The first-40-days tonic",
   "meaning": "Tradition, honestly labelled. Beet kvass is the everyday kitchen ferment of Eastern-European households — a small daily glass, long given to the run-down and the recovering, including new mothers.",
   "src": ["Traditional Eastern-European kitchen practice — a small daily glass of beet brine"]},
  "bf": {"cls": "b", "chip": "breastfeeding note", "title": "Kvass while breastfeeding",
   "meaning": "Breastfeeding note — a care flag, not a grade. A short brine ferment like this carries only trace alcohol (unlike sugary bread kvass) and is a food, not a supplement. It is salty — so it's a small-glass habit, and it counts toward flavour, not hydration. Start small and watch how you both feel.",
   "src": [BCCDC, "Traditional postpartum use — small daily amounts"]},
 },
 "boost": {"label": "Make it PP Gold (for yourself)", "items": [
   {"k": "ginger", "label": "a few slices of ginger in the jar", "small": "a warm edge", "on": True},
   {"k": "next", "label": "start the next jar the day you strain this one", "small": "an unbroken daily glass", "on": True},
  ], "note": "The strained beets still have life in them — they go into borscht."},
 "when_opts": {"label": "For", "opts": ["On waking", "Before lunch", "Before dinner"], "sel": "On waking"},
 "ings": [
  {"k": "beets", "n": "Organic beets", "q": "3 medium", "img": "img/beet-kvass-card/ing-01-organic-beets-diced.jpg", "prep": "diced, skin on — no peeling"},
  {"k": "salt", "n": "Sea salt — non-iodised", "q": "1½ level tbsp", "img": "img/beet-kvass-card/ing-02-sea-salt.jpg", "prep": "non-iodised only"},
  {"k": "water", "n": "Filtered water", "q": "to fill the jar", "img": "img/beet-kvass-card/ing-03-filtered-water.jpg"},
  {"k": "ginger", "n": "Fresh ginger", "q": "a few slices", "img": "img/beet-kvass-card/ing-04-a-few-slices-ginger.jpg", "opt": True},
 ],
 "method": [
  {"ic": "Fill the jar", "verb": "Beets &amp; salt into a clean jar",
   "detail": "Wash hands and use a <b>clean glass jar</b>. Dice <b>3 beets</b> (skin on) and fill the jar <b>one-third</b> full. Add <b>1½ level tbsp non-iodised salt</b> (+ ginger, if Mum asked).",
   "warn": {"b": "Non-iodised salt only.", "text": "Iodised or anti-caking salt can spoil the ferment — check the packet says sea salt or rock salt, nothing added."},
   "done": "a clean jar, one-third ruby cubes.",
   "say": "Wash your hands and use a clean glass jar. Dice the beets with the skin on, fill the jar one third full, and add the salt."},
  {"ic": "Add water", "verb": "Water to 2–3 cm below the rim",
   "detail": "Fill with <b>filtered water</b> to <b>2–3 cm below the rim</b>, and stir once to start the salt dissolving.",
   "warn": {"b": "Beets stay under the water.", "text": "Anything poking above the brine can grow mould — push strays back down."},
   "done": "beets under water, a little headroom at the top.",
   "say": "Fill with filtered water to just below the rim, and stir once. The beets must stay under the water."},
  {"ic": "Ferment", "verb": "Cover &amp; wait — 3 to 5 days",
   "detail": "Cover with a <b>cloth or loose lid</b>, and leave at room temperature, <b>out of the sun</b>. Once a day: stir, and push the beets back under. Taste from day 3 — it's ready when it's <b>tangy and earthy</b>.",
   "days": True,
   "warn": {"b": "Trust your nose.", "text": "Earthy and tangy is right. Mould on top, fizz gone wrong, or a smell that says no — don't drink it; tip it and start fresh."},
   "done": "deeper red and gently sour, day by day.",
   "say": "Cover the jar with a cloth and leave it at room temperature out of the sun. Once a day, stir and push the beets back under. Taste from day three."},
  {"ic": "Strain & chill", "verb": "Strain into a bottle — fridge",
   "detail": "When it tastes right: strain into a clean bottle and <b>refrigerate</b>. Mum has <b>a small glass a day</b>. The beets go on to borscht.",
   "done": "a ruby bottle in the fridge door.",
   "say": "Strain into a clean bottle and put it in the fridge. Mum has a small glass a day."},
 ],
 "overview_method": [
  "Clean jar: beets to ⅓, salt in.",
  "Water to 2–3 cm below the rim.",
  "Cloth on; 3–5 days; stir daily.",
  "Strain, bottle, fridge.",
 ],
 "nutri": [
  {"v": "Folate", "k": "from the beets"},
  {"v": "Live", "k": "lacto-cultures"},
  {"v": "Alcohol", "k": "essentially none"},
 ],
 "nutri_label": "In a small glass",
 "instr_note": "Made to your 1.6 L Kilner — the fill lines are the measure. Nothing to scale.",
},
]
