# -*- coding: utf-8 -*-
"""Batch 4 — gentle recovery mains (week-1 priority): chicken bone broth,
no-water magic chicken soup, khichdi.

Verdicts carried from TAXONOMY-SYNERGY.md:
- A.2 #1 (highest-value fix): broth reframed as COLLAGEN + GLYCINE + COMFORT +
  FLUIDS — no iron/mineral-rebuild claims anywhere; the honest 'minerals are
  modest' line lives in the sources sheet (Springer + PMC5533136).
- A.1 minor: star anise in the broth's warming swap stays culinary-only
  (one pod, strained, Chinese star anise) with the e-lactation source.
- Creator names removed from card copy (magic soup) per the locked rule.
- Khichdi = the ONE dial card here (ratio law): rice is the anchor, red lentils
  auto-follow 1:1; supporting cast scales off the total; serves ~3 scales;
  egg yolk (1 per bowl) and lemon are fixed. Bone broth + magic soup are
  pot/unit-bound → no dial.
"""

from data_teas import USDA, CAMBRIDGE_VITC, ODS_IRON, BANYAN, FFD
from data_mineral import BROTH_SPRINGER, BROTH_PMC, ODS_CHOLINE, INFANTRISK_CHOLINE

ELACT_STAR_ANISE = '<a href="https://www.e-lactation.com/en/star-anise-pr/" target="_blank" rel="noopener">e-lactation — star anise: culinary amounts only</a>'

DRINKS = [

# ---------------------------------------------------------------- chicken bone broth
{
 "slug": "chicken-bone-broth-card",
 "boost_prefix": "Your cup &amp; jar",
 "name": "Chicken Bone Broth",
 "eyebrow": "Bone broth <span class='dot'>·</span> Heal your gut <span class='dot'>·</span> The daily base",
 "sub": "Feet &amp; necks simmered low — deep collagen and warm comfort, a cup a day or the base of everything.",
 "hero_alt": "A big pot of golden chicken bone broth",
 "time": "2–3 hours, mostly unattended",
 "makes": "~3 L",
 "keep": "fridge ~4 days &middot; freeze in jars + ice-cube trays",
 "when_label": "When to drink",
 "when": "A warm cup a day, any time — or as the base for soups, khichdi and one-pots. It counts toward your fluids.",
 "meta_line": "2–3 hrs, mostly unattended &middot; makes ~<b>3 L</b>",
 "finish_head": "Jars filled?",
 "finish_btn": "Broth done &mdash; tell Mum",
 "finish_cap": "Mum gets a note that the week&rsquo;s base is ready.",
 "after_line": "Sent to Mum &mdash; the fridge is stocked.",
 "why": [
  {"text": "Chicken feet &amp; necks — the collagen parts: the pot sets to jelly when cold, and that wobble is the point", "chip": "rb", "ev": "collagen"},
  {"text": "Glycine-rich and easy to take — warmth and fluids on days eating feels like work", "chip": "rb", "ev": "collagen"},
  {"text": "Ginger, turmeric &amp; ajwain — the warming, digestion-kind spices", "chip": "t", "ev": "spices"},
  {"text": "The base of the week — khichdi, soups and grains all start from this pot"},
 ],
 "bfnote": {"text": "The broth itself is simply food. The one flag lives in the warming swap: star anise stays culinary — one pod, strained out, Chinese star anise only.", "ev": "bf"},
 "ev": {
  "collagen": {"cls": "rb", "chip": "research-backed", "title": "Broth — collagen &amp; glycine, honestly framed",
   "meaning": "Research-backed on composition — and honestly bounded. Long-simmered feet and necks measurably release collagen (gelatin) and glycine — that's why the chilled pot sets to jelly. What broth does NOT deliver much of is minerals or iron: analyses show those are modest and variable. So this card claims repair building-blocks, warmth and fluids — and leaves the iron story to the liver and meat cards.",
   "src": [BROTH_SPRINGER, BROTH_PMC]},
  "spices": {"cls": "t", "chip": "tradition", "title": "The warming pot spices",
   "meaning": "Tradition, honestly labelled. Ginger, turmeric, ajwain, garlic and bay are the warming, digestion-friendly seasonings of postpartum broths across kitchens — South Asian and European alike.",
   "src": ["Traditional postpartum-kitchen practice — warming spices in the daily broth", BANYAN]},
  "bf": {"cls": "b", "chip": "breastfeeding note", "title": "The star-anise swap — culinary only",
   "meaning": "Breastfeeding note — a care flag, not a grade. The PP-Gold warming swap (cinnamon stick + star anise) is lovely — with one rule: star anise stays at culinary dose. ONE pod, simmered and strained out, and make sure it's Chinese star anise (the baking kind from a normal shop). Star anise teas brewed strong are the thing to avoid while feeding.",
   "src": [ELACT_STAR_ANISE]},
  "gold": {"cls": "t", "chip": "tradition", "title": "The PP-Gold finish — dates, goji &amp; moringa",
   "meaning": "Tradition, honestly labelled. Red dates and goji simmered into the last minutes make it a confinement-style broth; a spoon of moringa stirred into your cup off the heat is the green finish from your own shelf. Warming tradition, not a trial claim.",
   "src": [FFD, "Traditional confinement-kitchen practice — red dates &amp; goji in the mother's broth"]},
 },
 "boost": {"label": "Make it PP Gold (for yourself)", "items": [
   {"k": "dates", "label": "7 split red dates + 1 tbsp goji, last 15 min", "small": "the confinement finish", "on": True},
   {"k": "moringa", "label": "½ tsp moringa in your cup, off the heat", "small": "the green boost", "on": False},
   {"k": "warm", "label": "swap the herbs for cinnamon + 1 star anise", "small": "one pod, strained — read the note", "on": False},
  ], "note": "These finish YOUR cup and jar — the base pot stays the family's."},
 "when_opts": {"label": "For", "opts": ["A warm cup today", "The week's cooking base"], "sel": "The week's cooking base"},
 "ings": [
  {"k": "feet", "n": "Chicken feet", "q": "4", "img": "img/chicken-bone-broth-card/ing-01-chicken-feet.jpg", "prep": "more if they fit"},
  {"k": "necks", "n": "Chicken necks", "q": "2", "img": "img/chicken-bone-broth-card/ing-02-chicken-necks.jpg"},
  {"k": "water", "n": "Cold water", "q": "3 L", "img": "img/chicken-bone-broth-card/ing-03-cold-water.jpg"},
  {"k": "vinegar", "n": "Apple cider vinegar", "q": "2 tbsp", "img": "img/chicken-bone-broth-card/ing-04-apple-cider-vinegar.jpg"},
  {"k": "ginger", "n": "Ginger powder", "q": "¾ tsp", "img": "img/chicken-bone-broth-card/ing-05-ginger-powder.jpg"},
  {"k": "turmeric", "n": "Turmeric powder", "q": "1 tsp", "img": "img/chicken-bone-broth-card/ing-06-turmeric-powder.jpg"},
  {"k": "pepper", "n": "Black peppercorns", "q": "½ tsp", "img": "img/chicken-bone-broth-card/ing-07-black-peppercorns.jpg"},
  {"k": "garlic", "n": "Garlic cloves", "q": "4, smashed", "img": "img/chicken-bone-broth-card/ing-08-garlic-cloves.jpg"},
  {"k": "ajwain", "n": "Ajwain seeds", "q": "½ tsp", "img": "img/chicken-bone-broth-card/ing-09-ajwain-seeds.jpg"},
  {"k": "bay", "n": "Bay leaves", "q": "2", "img": "img/chicken-bone-broth-card/ing-10-bay-leaves.jpg"},
  {"k": "herbs", "n": "Rosemary + thyme", "q": "a sprig each", "img": "img/chicken-bone-broth-card/ing-11-rosemary-thyme.jpg"},
  {"k": "salt", "n": "Salt", "q": "to taste", "img": "img/chicken-bone-broth-card/ing-12-salt.jpg"},
 ],
 "method": [
  {"ic": "Soak", "verb": "Soak — 30 min, no heat",
   "detail": "Chicken <b>feet, necks</b> and <b>3 L cold water</b> into the biggest pot, with <b>2 tbsp cider vinegar</b>. Let it sit — no heat yet.",
   "timer": [{"label": "Soak", "min": 30}],
   "cap": "The vinegar soak helps the bones give up their collagen.",
   "done": "bones sitting in cold, slightly sharp water.",
   "say": "Put the chicken feet, necks and cold water into the biggest pot with the cider vinegar, and let it sit with no heat."},
  {"ic": "Boil & skim", "verb": "Hard boil, skim the foam — 15 min",
   "detail": "Bring to a <b>hard boil</b>. Grey foam will rise — <b>scoop it off and throw it away</b> until the surface looks clean.",
   "timer": [{"label": "Boil &amp; skim", "min": 15}],
   "done": "a clean surface, no grey foam.",
   "say": "Bring it to a hard boil, and keep scooping off the grey foam until the surface looks clean."},
  {"ic": "Simmer low", "verb": "Bare simmer — 1½ to 2½ hours",
   "detail": "Turn right down to a <b>bare simmer</b> — the odd lazy bubble, never rolling. Add the <b>ginger, turmeric, peppercorns, garlic, ajwain, bay</b> and the <b>herb sprigs</b>. Top up with hot water now and then.",
   "timer": [{"label": "Simmer", "min": 90}],
   "cap": "Low and slow is the whole recipe — a hard boil makes it cloudy and bitter.",
   "done": "golden, smelling like the whole house is cared for.",
   "say": "Turn it right down to a bare simmer, add the spices and herbs, and top up with hot water now and then."},
  {"ic": "Season, strain & jar", "verb": "Salt, strain, into jars",
   "detail": "<b>Salt to taste</b>. Strain off the bones and pour into <b>jars</b> — some for the fridge, some for the freezer (ice-cube trays make cooking portions). If Mum asked: the <b>red dates + goji</b> go in for the last 15 min before straining.",
   "done": "a row of golden jars; it will set to jelly when cold — that's perfect.",
   "say": "Salt to taste, strain off the bones, and pour into jars for the fridge and freezer."},
 ],
 "overview_method": [
  "Soak bones + vinegar — 30 min, no heat.",
  "Hard boil; skim the grey foam.",
  "Bare simmer 1½–2½ h with the spices.",
  "Salt, strain, jar — fridge &amp; freezer.",
 ],
 "nutri": [
  {"v": "Collagen", "k": "sets to jelly · the proof"},
  {"v": "Fluids", "k": "a warm cup counts"},
  {"v": "Minerals", "k": "modest — we say so"},
 ],
 "nutri_label": "In a warm cup, honestly",
 "instr_note": "Made to the big pot — nothing to scale. Your helper's card matches this one.",
},

# ---------------------------------------------------------------- magic chicken soup
{
 "slug": "magic-chicken-soup",
 "boost_prefix": "Your bowl only",
 "name": "No-Water Magic Chicken Soup",
 "eyebrow": "No-water soup <span class='dot'>·</span> Heal your gut <span class='dot'>·</span> Sick-day deep",
 "sub": "No water added — a sealed pot lets cabbage, apple &amp; onion melt into the chicken and make their own golden broth.",
 "hero_alt": "A pot of no-water chicken soup with golden broth",
 "time": "about 1 hour, mostly the pot's work",
 "makes": "4 bowls",
 "keep": "fridge ~4 days &middot; freezes well",
 "when_label": "When to eat",
 "when": "Made for low, run-down days — a deeply concentrated broth. Sip the leftovers warm through the day.",
 "meta_line": "About 1 hr &middot; serves <b>4</b>",
 "finish_head": "All served?",
 "finish_btn": "Cooked &mdash; tell Mum",
 "finish_cap": "Mum gets a note on her phone that dinner&rsquo;s ready.",
 "after_line": "Sent to Mum &mdash; she knows dinner&rsquo;s ready.",
 "why": [
  {"text": "A whole chicken, gently steamed in its own juices — protein &amp; collagen, nothing diluted", "chip": "rb", "ev": "chicken"},
  {"text": "No added water — the cabbage, apple &amp; onion release their own intense golden broth"},
  {"text": "Red dates &amp; ginger — the warming confinement pair", "chip": "t", "ev": "confine"},
  {"text": "Gentle on a low appetite — the sick-day pot"},
 ],
 "bfnote": {"text": "Everything in the pot is everyday food while feeding. The chilli lives in the sauce, not the pot — it goes on your bowl only if you fancy it.", "ev": "bf"},
 "ev": {
  "chicken": {"cls": "rb", "chip": "research-backed", "title": "Whole chicken — protein, undiluted",
   "meaning": "Research-backed on composition. A whole chicken steamed with no added water keeps its protein and collagen in the pot — the broth is concentrated because nothing was poured in. (As with all broths, minerals stay modest — the protein is the point.)",
   "src": [USDA("chicken, whole (nutrient data)"), BROTH_SPRINGER]},
  "confine": {"cls": "t", "chip": "tradition", "title": "Red dates &amp; ginger — the confinement pair",
   "meaning": "Tradition, honestly labelled. Red dates and ginger are the classic warming pair of the East-Asian confinement kitchen, dropped into the mother's soups through the first month. Centuries of practice; labelled as the tradition it is.",
   "src": [FFD, "Traditional East-Asian confinement practice — dates &amp; ginger in the mother's pot"]},
  "bf": {"cls": "b", "chip": "breastfeeding note", "title": "The pot, the sauce &amp; the chilli",
   "meaning": "Breastfeeding note — a care flag, not a grade. The pot itself is everyday food. The ginger-scallion sauce is too. The chilli is simply your choice — it seasons your bowl, so keep it out of the shared pot and add it to yours. For a toddler: plain shredded chicken and broth over rice, no sauce.",
   "src": ["House rule — season the bowl, not the pot, so every eater chooses"]},
 },
 "serve": {"label": "Your bowl — serve with", "items": [
   {"k": "sauce", "label": "the ginger-scallion sauce", "on": True},
   {"k": "chilli", "label": "chilli on your bowl", "on": False},
   {"k": "rice", "label": "a scoop of rice in the broth", "on": False},
  ]},
 "boost": {"label": "Make it PP Gold (for yourself)", "items": [
   {"k": "dates", "label": "2–3 extra red dates + 1 tbsp goji", "small": "the confinement finish", "on": True},
   {"k": "feet", "label": "a few chicken feet under the birds", "small": "extra collagen", "on": False},
  ], "note": "For toddlers: plain shredded chicken &amp; broth over rice — skip the sauce."},
 "when_opts": {"label": "Ready for", "opts": ["Lunch", "Dinner"], "sel": "Dinner"},
 "ings": [
  {"k": "chicken", "n": "Whole chickens", "q": "2 small", "img": "img/magic-chicken-soup/ing-01-whole-chickens.jpg", "prep": "~800 g each, or 1 small chicken"},
  {"k": "cabbage", "n": "Napa cabbage", "q": "½ head", "img": "img/magic-chicken-soup/ing-02-napa-cabbage.jpg", "prep": "chopped"},
  {"k": "apple", "n": "Apple", "q": "1", "img": "img/magic-chicken-soup/ing-03-apple.jpg", "prep": "chopped"},
  {"k": "onion", "n": "Onion", "q": "1", "img": "img/magic-chicken-soup/ing-04-onion.jpg", "prep": "sliced"},
  {"k": "dates", "n": "Red dates", "q": "3", "img": "img/magic-chicken-soup/ing-05-red-dates.jpg", "prep": "halved, stones out"},
  {"k": "ginger", "n": "Fresh ginger", "q": "3 slices", "img": "img/magic-chicken-soup/ing-06-fresh-ginger.jpg"},
  {"k": "salt", "n": "Sea salt", "q": "1 tsp", "img": "img/magic-chicken-soup/ing-07-sea-salt.jpg"},
  {"k": "scallion", "n": "Spring onion", "q": "2 stalks", "img": "img/magic-chicken-soup/ing-08-spring-onion.jpg", "prep": "1 for the pot, 1 for the sauce"},
  {"k": "soy", "n": "Soy sauce", "q": "2 tbsp", "img": "img/magic-chicken-soup/ing-09-soy-sauce.jpg", "prep": "or tamari — for the sauce"},
  {"k": "oil", "n": "Oil", "q": "1 tbsp", "img": "img/magic-chicken-soup/ing-10-oil.jpg", "prep": "sesame or olive — for the sauce"},
  {"k": "chilli", "n": "Red chilli", "q": "1", "img": "img/magic-chicken-soup/ing-11-red-chilli.jpg", "opt": True, "prep": "for Mum's bowl only"},
 ],
 "method": [
  {"ic": "Layer the pot", "verb": "Layer — veg below, birds on top",
   "detail": "In a heavy pot: <b>onion, apple, napa cabbage, red dates, ginger, salt</b> — then sit the <b>whole chickens</b> on top. <b>No water goes in.</b>",
   "done": "birds sitting on a bed of veg, pot dry.",
   "say": "Layer the onion, apple, cabbage, red dates, ginger and salt in a heavy pot, and sit the chickens on top. No water goes in."},
  {"ic": "Seal & cook", "verb": "Lid on tight — 60 min low",
   "detail": "Cover <b>tightly</b> and cook on <b>low</b>. The sealed steam pulls a golden broth out of the veg — that IS the soup.",
   "timer": [{"label": "Cook", "min": 60}],
   "warn": {"b": "The lid stays on.", "text": "Every peek lets the broth escape as steam — trust the pot until the timer rings."},
   "done": "the pot half-full of golden broth that wasn't there before.",
   "say": "Cover the pot tightly and cook on low. The lid stays on — every peek lets the broth escape."},
  {"ic": "Rest & serve", "verb": "Lift, ladle, scatter",
   "detail": "Heat off. Lift out the tender chicken, spoon the veg into bowls, and ladle the <b>self-made broth</b> over. Scatter <b>spring onion</b>.",
   "done": "bowls of chicken and veg under golden broth.",
   "say": "Turn off the heat. Lift out the chicken, spoon out the veg, and ladle the broth over. Scatter spring onion."},
  {"ic": "Ginger-scallion sauce", "verb": "The 2-minute sauce",
   "detail": "Heat <b>1 tbsp oil</b> until shimmering; pour it over the minced <b>ginger &amp; spring onion</b> in a small bowl. Stir in <b>2 tbsp soy sauce</b>. Chilli goes on <b>Mum's bowl only</b>, if she asked.",
   "done": "a glossy little bowl of sauce, spooned over.",
   "say": "Heat the oil until it shimmers, pour it over the minced ginger and spring onion, and stir in the soy sauce. Chilli only on Mum's bowl, if she asked."},
 ],
 "overview_method": [
  "Layer veg, dates &amp; ginger; birds on top — no water.",
  "Lid on tight; 60 min low.",
  "Lift, ladle the golden broth, scatter scallion.",
  "Hot-oil ginger-scallion sauce; chilli = Mum's bowl only.",
 ],
 "nutri": [
  {"v": "Protein", "k": "a whole chicken"},
  {"v": "Broth", "k": "concentrated · sip it"},
  {"v": "Gentle", "k": "the sick-day pot"},
 ],
 "nutri_label": "In a bowl, roughly",
 "instr_note": "Made to its pot — one chicken (or two small), no scaling to set.",
},

# ---------------------------------------------------------------- khichdi (THE dial card)
{
 "slug": "khichdi",
 "boost_prefix": "Your bowl only",
 "name": "Khichdi — the gentle one-pot",
 "eyebrow": "One-pot <span class='dot'>·</span> Heal your gut <span class='dot'>·</span> First-weeks food",
 "sub": "Soft rice and red lentils simmered in bone broth — the Ayurvedic first-food, simple enough to hand to anyone.",
 "hero_alt": "A bowl of soft golden khichdi with ghee",
 "time": "about 35 min",
 "makes": "~3 bowls",
 "keep": "2 days — reheat with a splash of broth",
 "when_label": "When to eat",
 "when": "Lunch or dinner from the very first week home — the softest complete meal for tired, tender days.",
 "meta_line": "About 35 min &middot; serves ~<b id=\"makesN\">3</b>",
 "finish_head": "All served?",
 "finish_btn": "Cooked &mdash; tell Mum",
 "finish_cap": "Mum gets a note on her phone that dinner&rsquo;s ready.",
 "after_line": "Sent to Mum &mdash; she knows dinner&rsquo;s ready.",
 "dial": {
   "anchor": {"label": "White rice", "base": 0.5, "unit": "cup", "min": 0.25, "max": 1.5, "step": 0.25},
   "follow": {"label": "Red lentils", "base": 0.5, "unit": "cup", "min": 0.25, "max": 1.5, "step": 0.25},
   "ratio": 1.0,
   "balanced_line": "Balanced to the recipe &mdash; equal rice and red lentils.",
   "more_line": "More lentils than the recipe &mdash; heartier and denser.",
   "less_line": "Less lentils than the recipe &mdash; softer, more of a rice porridge.",
   "makes_base": 3,
 },
 "why": [
  {"text": "Rice + split red lentils — together a complete protein, soft and easy to digest", "chip": "rb", "ev": "protein"},
  {"text": "The Ayurvedic first-food for recovery — the first pot the tradition puts on the stove", "chip": "t", "ev": "ayur"},
  {"text": "Ghee, cumin &amp; ajwain — the classic trio for settling digestion", "chip": "t", "ev": "ayur"},
  {"text": "Simmered in bone broth, finished with an egg yolk — collagen blocks, protein &amp; choline in the bowl", "chip": "rb", "ev": "bowl"},
  {"text": "A squeeze of lemon — vitamin C helps your body absorb the lentils' iron", "chip": "rb", "ev": "vitc"},
 ],
 "bfnote": {"text": "Everything in the pot is breastfeeding-safe — this is the pot to hand over blind. The one care point is the yolk: it stays barely-cooked in the hot bowl, so use the freshest eggs.", "ev": "bf"},
 "ev": {
  "protein": {"cls": "rb", "chip": "research-backed", "title": "Rice + dal — a complete protein",
   "meaning": "Research-backed, established nutrition. Grains and pulses complete each other's amino acids — rice with red lentils delivers a complete protein in the softest possible form. That's why this pairing IS the recovery food across half the world's kitchens.",
   "src": [USDA("rice &amp; red lentils (protein &amp; amino-acid data)"), "Established nutrition — grain + pulse amino-acid complementation"]},
  "ayur": {"cls": "t", "chip": "tradition", "title": "Khichdi — the Ayurvedic first-food",
   "meaning": "Tradition, honestly labelled. Khichdi is what Ayurveda actually puts in front of a new mother first: soft, warm, spiced for digestion (ghee, cumin, ajwain), eaten through the 42-day window. Centuries of postpartum canon — labelled as the tradition it is.",
   "src": [BANYAN, "Classical Ayurvedic postpartum practice — khichdi through the sutika window"]},
  "bowl": {"cls": "rb", "chip": "research-backed", "title": "The broth &amp; the yolk — what they really add",
   "meaning": "Research-backed on composition. Cooking the pot in bone broth adds collagen-derived protein (the repair building-blocks — minerals in broth stay modest, and we say so). The egg yolk stirred into your hot bowl adds real protein and choline — the nutrient breastfeeding draws hardest on.",
   "src": [ODS_CHOLINE, BROTH_SPRINGER]},
  "vitc": {"cls": "rb", "chip": "research-backed", "title": "Lemon — vitamin C unlocks plant iron",
   "meaning": "Research-backed. Vitamin C alongside plant (non-heme) iron reliably increases how much your body absorbs — the lemon finish is doing quiet work on the lentils' iron.",
   "src": [CAMBRIDGE_VITC, ODS_IRON]},
  "bf": {"cls": "b", "chip": "breastfeeding note", "title": "The khichdi pot while feeding",
   "meaning": "Breastfeeding note — a care flag, not a grade. Everything in this pot is everyday food while nursing — it's the definition of a safe hand-over dinner. The one care point: the egg yolk cooks to silk in the hot bowl but stays barely-cooked, so use the freshest eggs you have (or pasteurised), and stir it in while the bowl is properly hot.",
   "src": [ODS_CHOLINE, "Standard food-safety practice — barely-cooked yolks want the freshest eggs"]},
 },
 "boost": {"label": "Make it PP Gold (for yourself)", "items": [
   {"k": "yolk", "label": "the egg yolk in your hot bowl", "small": "protein &amp; choline — it cooks to silk", "on": True},
   {"k": "moringa", "label": "1 tsp moringa, off the heat", "small": "the green boost from your shelf", "on": False},
   {"k": "ghee", "label": "extra ghee to finish", "small": "the classical way", "on": True},
  ], "note": "These finish your bowl only — the pot stays as gentle as it started."},
 "when_opts": {"label": "Ready for", "opts": ["Lunch", "Dinner"], "sel": "Dinner"},
 "ings": [
  {"k": "rice", "n": "White rice", "q": "½ cup", "img": "img/khichdi/ing-01-white-rice.jpg", "base": 0.5, "unit": "cup", "drive": "anchor"},
  {"k": "lentils", "n": "Split red lentils", "q": "½ cup", "img": "img/khichdi/ing-02-split-red-lentils.jpg", "prep": "or yellow moong dal", "base": 0.5, "unit": "cup", "drive": "follow"},
  {"k": "broth", "n": "Chicken bone broth", "q": "4 cups", "img": "img/khichdi/ing-03-chicken-bone-broth.jpg", "prep": "or water", "base": 4, "unit": "cup", "drive": "total"},
  {"k": "ghee", "n": "Ghee", "q": "1½ tbsp", "img": "img/khichdi/ing-04-ghee.jpg", "prep": "+ extra to finish", "base": 1.5, "unit": "tbsp", "drive": "total"},
  {"k": "cumin", "n": "Cumin seeds", "q": "1 tsp", "img": "img/khichdi/ing-05-cumin-seeds.jpg", "base": 1, "unit": "tsp", "drive": "total"},
  {"k": "ajwain", "n": "Ajwain seeds", "q": "½ tsp", "img": "img/khichdi/ing-06-ajwain-seeds.jpg", "base": 0.5, "unit": "tsp", "drive": "total"},
  {"k": "ginger", "n": "Fresh ginger", "q": "2 cm, grated", "img": "img/khichdi/ing-07-fresh-ginger-grated.jpg"},
  {"k": "turmeric", "n": "Turmeric", "q": "½ tsp", "img": "img/khichdi/ing-08-turmeric.jpg", "base": 0.5, "unit": "tsp", "drive": "total"},
  {"k": "salt", "n": "Salt", "q": "¾ tsp", "img": "img/khichdi/ing-09-salt.jpg", "base": 0.75, "unit": "tsp", "drive": "total"},
  {"k": "spinach", "n": "Spinach", "q": "~2 handfuls", "img": "img/khichdi/ing-10-spinach.jpg", "base": 2, "unit": "handful", "drive": "total"},
  {"k": "yolk", "n": "Egg yolk", "q": "1 per bowl", "img": "img/khichdi/ing-11-egg-yolk.jpg", "prep": "stirred in hot — it cooks to silk"},
  {"k": "lemon", "n": "Lemon", "q": "½, to finish", "img": "img/khichdi/ing-12-lemon-to-finish.jpg"},
 ],
 "method": [
  {"ic": "Rinse", "verb": "Rinse the rice &amp; lentils",
   "detail": "Rinse <b><span data-base=\"0.5\" data-unit=\"cup\" data-drive=\"anchor\">½ cup</span> rice</b> and <b><span data-base=\"0.5\" data-unit=\"cup\" data-drive=\"follow\">½ cup</span> red lentils</b> together in a sieve until the water runs nearly clear.",
   "done": "rinse water running nearly clear.",
   "say": "Rinse the rice and red lentils together in a sieve until the water runs nearly clear."},
  {"ic": "Bloom the spices", "verb": "Sizzle the spices in ghee — 1 min",
   "detail": "Melt <b><span data-base=\"1.5\" data-unit=\"tbsp\" data-drive=\"total\">1½ tbsp</span> ghee</b> in the pot. Sizzle the <b>cumin</b> and <b>ajwain</b> for 30 seconds, then stir in the <b>grated ginger</b> and <b>turmeric</b>.",
   "done": "seeds crackling, kitchen smelling warm.",
   "say": "Melt the ghee, sizzle the cumin and ajwain briefly, then stir in the ginger and turmeric."},
  {"ic": "Simmer", "verb": "Lazy simmer — 25–30 min",
   "detail": "Add the <b>rice, lentils</b>, <b><span data-base=\"4\" data-unit=\"cup\" data-drive=\"total\">4 cups</span> bone broth</b> and the <b>salt</b>. A <b>lazy simmer</b>, lid half on, until soft and porridge-like.",
   "timer": [{"label": "Simmer", "min": 25}],
   "cap": "The only rule of this pot: a lazy simmer, never a hard boil. Too thick? A splash of hot water.",
   "done": "soft and porridge-like — a spoon stands up lazily.",
   "say": "Add the rice, lentils, broth and salt, and keep it at a lazy simmer with the lid half on until soft and porridge-like."},
  {"ic": "Greens in", "verb": "Spinach — the last 5 min",
   "detail": "Stir <b><span data-base=\"2\" data-unit=\"handful\" data-drive=\"total\">~2 handfuls</span> spinach</b> through for the final minutes.",
   "timer": [{"label": "Greens", "min": 5}],
   "done": "green folded through the gold.",
   "say": "Stir the spinach through for the last few minutes."},
  {"ic": "Finish Mum's bowl", "verb": "Mum's bowl — yolk, lemon, ghee",
   "detail": "Off the heat: stir <b>1 egg yolk</b> into Mum's <b>hot</b> bowl — it cooks to silk — then a <b>squeeze of lemon</b> and a little <b>extra ghee</b>.",
   "warn": {"b": "The yolk stays barely cooked.", "text": "Use the freshest egg, and stir it into a properly hot bowl."},
   "done": "one silky, golden bowl for Mum; the pot plain for everyone else.",
   "say": "Off the heat, stir an egg yolk into Mum's hot bowl, then add a squeeze of lemon and a little extra ghee."},
 ],
 "overview_method": [
  "Rinse rice + lentils till clear.",
  "Sizzle cumin &amp; ajwain in ghee; ginger + turmeric in.",
  "Broth in; lazy simmer 25–30 min.",
  "Spinach the last 5.",
  "Mum's bowl: yolk + lemon + ghee.",
 ],
 "nutri": [
  {"v": "Complete", "k": "protein · rice + dal"},
  {"v": "Choline", "k": "the yolk finish"},
  {"v": "Soft", "k": "first-week gentle"},
 ],
 "nutri_label": "In a bowl, roughly",
 "instr_note": "The rice dial sets the pot — lentils follow at the recipe's 1:1; everything else scales with them.",
},
]
